module.exports = {
  getRandomElement(arr){
    return arr[Math.floor(Math.random() * arr.length)];
  },
  findUniqueTopics(arr1, arr2){
    let t1 = this.getRandomElement(arr1);
    let t2 = this.getRandomElement(arr2);
    if(t1 !== t2){
      return [t1, t2];
    }else{
      return this.findUniqueTopics(arr1, arr2);
    }
  },
  replaceInvalidTopics(arr){
    return arr.map(cur=>{
      if(!cur) cur = '/wiki/JavaScript';
      return cur;
    });
  },
  topics(){
    // link: https://en.wikipedia.org/wiki/Wikipedia:Lists_of_popular_pages_by_WikiProject
    // skipping href that links to inappropriate or inapplicable topics
    return [
      'Academic_Journals',
      'Actors_and_Filmmakers',
      'Albums',
      'Amphibians_and_Reptiles',
      'Animals',
      'Animals_in_media',
      'Animation',
      'Alternative_music',
      'Architecture',
      'Arthropods',
      'Astronomical_objects',
      'Athletics',
      'Automobiles',
      'Bible',
      'Bivalves',
      'Boxing',
      'Brands',
      'Buddhism',
      'Business',
      'Cartoon_Network',
      'Chemicals',
      'Chemistry',
      'Cetaceans',
      'Christianity',
      'Cities',
      'Classical_Greece_and_Rome',
      'Classical_music',
      'Color',
      'Companies',
      'Composers',
      'Computer_science',
      'Computing',
      'Countries',
      'Dance',
      'Databases',
      'Dogs',
      'Economics',
      'Elements',
      'Energy',
      'Engineering',
      'Environment',
      'Fictional_characters',
      'Film',
      'Finance',
      'Fishes',
      'Food_and_Drink',
      'Free_software',
      'Genetics',
      'Gastropods',
      'Graphic_design',
      'Hinduism',
      'Hip_hop',
      'History',
      'Human_rights',
      'Investment',
      'Islands',
      'Isotopes',
      'Judaism',
      'Islam',
      'Marketing_%26_Advertising',
      'Mathematics',
      'Mammals',
      'Michael_Jackson',
      'Military_history',
      'Military_history/American_Civil_War_task_force',
      'Military_history/American_Revolutionary_War_task_force',
      'Molecular_and_Cell_Biology',
      'Musicians',
      'Multi-sport_events',
      'Mountains',
      'Neuroscience',
      'Novels',
      'Philosophy',
      'Philosophy/Ancient',
      'Philosophy/Eastern',
      'Philosophy/Religion',
      'Physics',
      'Plants',
      'Primates',
      'Psychology',
      'Religion',
      'Retailing',
      'Science',
      'Shakespeare',
      'Ships',
      'Solar_System',
      'Social_Work',
      'Sharks',
      'Statistics',
      'Taxation',
      'Technology',
      'Telecommunications',
      'Television',
      'United_States',
      'Video_games',
      'Visual_arts',
      'Volcanoes',
      'Websites',
      'Women%27s_History',
      'Turtles',
      'Spiders'
    ];
  }
};